import 'package:final_project_beamin_app/model/user.dart';

class Store {
  int id;
  String category;
  String name;
  String? phone;
  String thumbnail;
  String? ceoName;
  String? businessNumber;
  String? businessAddress;
  String? openTime;
  String? closeTime;
  int? minAmount;
  String deliveryHour;
  int? deliveryCost;
  String intro;
  String? notice;
  double starPoint;
  bool isOpend;
  bool isAccept;
  bool isClosure;
  User? user;

  Store({
    required this.id,
    required this.category,
    required this.name,
    this.phone,
    required this.thumbnail,
    this.ceoName,
    this.businessNumber,
    this.businessAddress,
    this.openTime,
    this.closeTime,
    this.minAmount,
    required this.deliveryHour,
    this.deliveryCost,
    required this.intro,
    this.notice,
    required this.starPoint,
    required this.isOpend,
    required this.isAccept,
    required this.isClosure,
    this.user,
  });
}

List<Store> storeList = [
  Store(
    id: 1,
    category: "치킨",
    name: "네네치킨 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/치킨.jpg",
    ceoName: "엄복동",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-4",
    openTime: "09",
    closeTime: "21",
    minAmount: 17000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "굽네치킨 시켜먹어라",
    notice: "굽네치킨 시켜먹으세요 여기 노맛임",
    starPoint: 4,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 2,
    category: "치킨",
    name: "굽네치킨 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/category/양념치킨.jpg",
    ceoName: "엄복동",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-4",
    openTime: "09",
    closeTime: "21",
    minAmount: 17000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "네네치킨 시켜먹어라",
    notice: "네네치킨 시켜먹으세요 여기 노맛임",
    starPoint: 5,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 3,
    category: "피자",
    name: "도미노 피자 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/피자.jpg",
    ceoName: "피자 알볼로",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-5",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "피자 알볼로 먹어라",
    notice: "피자 알볼로 먹어라",
    starPoint: 3,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 4,
    category: "피자",
    name: "피자 알볼로 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/피자.jpg",
    ceoName: "도미노 피자",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-5",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "도미노 피자 먹어라",
    notice: "도미노 피자 먹어라 여기 노맛임",
    starPoint: 4,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 5,
    category: "버거",
    name: "롯데리아 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/버거.png",
    ceoName: "맥도날드",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-6",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "맥도날드 먹어라",
    notice: "맥도날드 먹어라 여기 맛없다.",
    starPoint: 2,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 6,
    category: "버거",
    name: "맥도날드 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/버거.png",
    ceoName: "롯데리아",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-7",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "롯데리아 먹어라",
    notice: "롯데리아 먹어라 여기 맛없다.",
    starPoint: 3,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 7,
    category: "분식",
    name: "죠스 떡볶이 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/떡볶이.jpg",
    ceoName: "신전 떡볶이",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-8",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "신전 떡볶이 먹어라",
    notice: "신전 떡볶이 먹어라 여기 맛없다.",
    starPoint: 2,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 8,
    category: "분식",
    name: "신전 떡볶이 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/떡볶이.jpg",
    ceoName: "죠스 떡볶이",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1234-9",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "죠스 떡볶이 먹어라",
    notice: "죠스 떡볶이 먹어라 여기 맛없다.",
    starPoint: 2,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 9,
    category: "한식",
    name: "본 비빔밥 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/비빔밥.jpg",
    ceoName: "본 비빔밥",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1235-1",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "한솥 도시락 먹어라",
    notice: "한솥 도시락 먹어라 여기 맛없다.",
    starPoint: 4,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
  Store(
    id: 10,
    category: "한식",
    name: "한솥 도시락 김해 외동점",
    phone: "055-000-0000",
    thumbnail: "assets/images/store/비빔밥.jpg",
    ceoName: "한솥 도시락",
    businessNumber: "1234567890",
    businessAddress: "김해시 외동 1235-2",
    openTime: "09",
    closeTime: "21",
    minAmount: 12000,
    deliveryHour: "25 ~ 30 분",
    deliveryCost: 3000,
    intro: "본 비빔밥 먹어라",
    notice: "본 비빔밥 먹어라 여기 맛없다.",
    starPoint: 3,
    isOpend: true,
    isAccept: true,
    isClosure: false,
    user: User(id: 2, username: "cos"),
  ),
];
